default_data.json

common, metadata and kfserving

Added more kubeflow projects

---

default_data.json

Add user Feng Xin

---

default_data.json

End the Huawei and start the Futurewei company
affiliation for:
* Matt Riedemann
* Melvin Hillsman
* Lance Bragstad
* Sean McGinnis
* Davanum Srinivas
Since Sean and Melvin had huawei emails registered
their futurewei email is added.

Add Futurewei company affiliation

---

default_data.json

add new member from H3C

---

default_data.json

Adding "kevin carter" user and updated company affiliations.
Signed-off-by: Kevin Carter <kecarter@redhat.com>

add user and company affiliation

---

default_data.json

Couldn't discern a sorting order, let me know if I need to fix!
Weirdly my user name is [Liam WHite](https://www.stackalytics.com/unaffiliated?project_type=istio-group&release=all&metric=commits&start_date=1547316440&end_date=1562864840&date=180&user_id=liamawhite).
Signed-off-by: Liam White <liam@tetrate.io>

Add new user Liam White

---

default_data.json

New user was added to default_data.json

New user was added

---

default_data.json

I want to change my email. Please help approve. Thanks!

change email

---

default_data.json

add dragonfly repo

---

default_data.json

Signed-off-by: 928234269 <longfei.shang@daocloud.io>

add my_count company_name

---

default_data.json

- Indicate departure from Rackspace
- Indicate period of unpaid OpenStack work
- Indicate new employment with Verizon Media

Update information for Jay Faulkner

---

default_data.json

- Indicate departure from IBM
- Indicate period of unpaid OpenStack work
- Indicate new employment with Red Hat
- Update emails
Signed-off-by: Flavio Fernandes <flaviof@redhat.com>

Update information for Flavio Fernandes

---

default_data.json

Add user Jane Man to default_data.json

Added Jane Man

---

default_data.json

Add new user andrebeltrami

---

default_data.json

add new user to default_data; please approve it; thx

Add new user  41tair

---

default_data.json

fix Bloomberg LP entry

---

default_data.json

Add DaoCloud users weiweizhu.

---

default_data.json

Please let know if rebase is needed :)

add Racnher Labs User

---

default_data.json

Employees at Rancher that haven't been using their Rancher email

Add Rancher Labs users

---

default_data.json

Add email and company information

Add account info for hemanth-n

---

default_data.json

added email and company affiliation

add my account info

---

default_data.json

I am changing my affiliation to better reflect my current employer.

Change affliation of user sagarun

---

default_data.json

Signed-off-by: Dao Cong Tien <tiendc@vn.fujitsu.com>

Add user tiendc

---

default_data.json

This commit reflects my affiliation change.

Change affiliation of Masayuki

---

default_data.json

Signed-off-by: Nguyen Hai Truong <truongnh@fujitsu.com>

Insert another email of Nguyen Hai Truong

---

default_data.json

The KubeFlow organization recently added few new projects. Therefore, we want to add those projects into the KubeFlow org tracking list.

Update list of KubeFlow repositories

---

default_data.json

Add user ckadner

---

default_data.json

As I have changed my job, old item must be cleaned. Otherwise,  stackalytics will show invalid info.

Remove old user

---

default_data.json

Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

Update affiliation of Nicolas Bock

---

default_data.json

Add launchpad_id for user ckadner

---

default_data.json

update my company

---

default_data.json

Add myself (@jasonvanbrackel) to users to match with Rancher.  Add the Longhorn project (https://longhorn.io/) to cncf projects

Add JvB to Users; Add Longhorn CNCF Project

---

default_data.json

Add projects missed in longhorn PR from earlier this week

Add longhorn projects and longhorn-group

---

default_data.json

Signed-off-by: Antonio Ojea <antonio.ojea.garcia@gmail.com>

update Antonio Ojea profile

---

default_data.json

add user dohan0930 to default_data.json

add user dohan0930

---

default_data.json

Add user hanjoo.cho

---

default_data.json

Update the company info about SataQiu.

Update the company info about SataQiu

---

default_data.json

Edit launchpad_id hanjoo.cho to hanjoo

Edit launchpad_id hanjoo.cho to hanjoo

---

default_data.json

add user chky

---

default_data.json

Add: user epdlemflaj

---

default_data.json

Added Stavros to users

---

default_data.json

Signed-off-by: shaowenchen <mail@chenshaowen.com>

Add a user and company

---

default_data.json

Reverts stackalytics/default_data#240

Revert "Added users"

---

default_data.json

Reverts stackalytics/default_data#241

Revert "Revert "Added users""

---

default_data.json

Signed-off-by: shaowenchen <mail@chenshaowen.com>

remove user
